---
abstract: 'interact with RabbitMQ over AMQP using librabbitmq'
author:
  - 'Mark Ellis <nobody@cpan.org>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: mozilla
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-AMQP-RabbitMQ
no_index:
  directory:
    - t
    - inc
resources:
  bugtracker: https://github.com/markwellis/net-amqp-rabbitmq/issues
  repository: git://github.com/markwellis/net-amqp-rabbitmq.git
version: '0.005001'
