---
abstract: 'interact with RabbitMQ over AMQP using librabbitmq'
author:
  - 'Theo Schlossnagle <jesus@omniti.com>'
  - 'Mark Ellis <nobody@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.133380'
license: mozilla
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-AMQP-RabbitMQ
no_index:
  directory:
    - t
    - inc
resources:
  bugtracker: https://github.com/n0body-/net-amqp-rabbitmq/issues
  repository: git://github.com/n0body-/net-amqp-rabbitmq.git
version: 0.003
